#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$app = new \PhpExchange\Console\Application();
$container = new \Symfony\Component\DependencyInjection\ContainerBuilder();

$app->setContainer($container);

$app->run();

